development: &development
  protocol: 'https'
  # host: 127.0.0.1
  # port: 5984
  host: 907f5bf9-d985-4c95-85d8-d5f34ee51a3f-bluemix.cloudant.com
  port: 443
  prefix: rent_couch
  suffix: di
  # username: root
  # password: groot
  username: andiberistartanyuedencro
  password: efa0cb252fdb58f674a84f40b2a07e03f137731f

test:
  <<: *development
  suffix: test

production:
  protocol: 'https'
  # host: 127.0.0.1
  # port: 5984
  host: 907f5bf9-d985-4c95-85d8-d5f34ee51a3f-bluemix.cloudant.com
  port: 443
  prefix: rent_couch
  suffix: di
  username: andiberistartanyuedencro
  password: efa0cb252fdb58f674a84f40b2a07e03f137731f