require 'couchrest_model'

class User < CouchRest::Model::Base
	include ActiveModel::SecurePassword

	# property :id,	Integer
	property :email,      String
	# property :password,      String
	property :username,      String
	property :name,      String
	property :surname,      String
	property :phone,      String
	property :surname,      String
	property :role_id,      Integer
	property :password_digest,		String
	# propery :password_confirmation	
	#  With timestamps! we are telling the model to create autogenerated fields for created_at and updated_at.

	collection_of :items

	validates_presence_of :email, :name, :surname, :password_digest, :role_id

	design do
		view :by_email
		# view :all_items_i_have
			 # :map =>
			 # "function(doc) {
		  #         if (doc.item_ids.length > 0) {
			 #            doc.item_ids.forEach(function(item_id){
			 #            	TODO
			 #              emit(doc.order, 1);
		  #           });
		  #         }
	   #      }"	
	end
	has_secure_password

	timestamps!

	# has_many :items, dependent: :destroy
	# TODO: does has_secure_password work with couchdb model?

 	# validates_presence_of :email, :name, :surname, :password_digest, :role_id
end